const MODULE = 'MARVEL_CHARACTER_MODULE';

const FETCH_CHARACTER_DETAIL_START = `${MODULE}_FETCH_CHARACTER_DETAIL_START`;
const FETCH_CHARACTER_DETAIL_SUCCESS = `${MODULE}_FETCH_CHARACTER_DETAIL_SUCCESS`;
const FETCH_CHARACTER_DETAIL_ERROR = `${MODULE}_FETCH_CHARACTER_DETAIL_ERROR`;

export {
  FETCH_CHARACTER_DETAIL_START,
  FETCH_CHARACTER_DETAIL_SUCCESS,
  FETCH_CHARACTER_DETAIL_ERROR
}