const MODULE = 'MARVEL_HOME_MODULE';

const FETCH_ALL_CHARACTERS_START = `${MODULE}_FETCH_ALL_CHARACTERS_START`;
const FETCH_ALL_CHARACTERS_SUCCESS = `${MODULE}_FETCH_ALL_CHARACTERS_SUCCESS`;
const FETCH_ALL_CHARACTERS_ERROR = `${MODULE}_FETCH_ALL_CHARACTERS_ERROR`;

export {
  FETCH_ALL_CHARACTERS_START,
  FETCH_ALL_CHARACTERS_SUCCESS,
  FETCH_ALL_CHARACTERS_ERROR
}